export const MAX_CONTEXT_CONTENT_LENGTH = 60000;
export const MAX_MCP_NAV_CONTENT_LENGTH = 30000;
export const MAX_AGENT_DEBUG_CONTENT_LENGTH = 20000;
export const MAX_COMPACT_CONTEXT_SNIPPET = 1200;
export const MAX_LISTING_DETECT_SNIPPET = 2000;
export const MAX_LISTING_CONTENT_FALLBACK = 3000;
export const MAX_ACCESS_ISSUE_CONTEXT = 6000;

export const LLAMA_CPP_MIN_CTX_TOKENS = 16384;
export const LLAMA_CPP_RECOMMENDED_CTX_TOKENS = 32768;
